### ISSUE TITLE
playout not generating new timestamps from source to output

### ISSUE THREAD

**Issue by edwoodza** [ffplayout/ffplayout_engine#98]
It appears the playout passes the timestamps of playout files and does not create new timestamped output.

So when pushing UDP out, output breaks as new file is played when using CBR

Please can you confirm as i do not know how the workings of playout works before it reaches the the section for encoding for output

VLC shows the following errors:
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 7) for PID 17
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 13) for PID 0
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 13) for PID 7166
main error: Timestamp conversion failed (delay 500000, buffering 0, bound 9000000)
main error: Could not convert timestamp 250412224267 for FFmpeg
main error: Timestamp conversion failed (delay 500000, buffering 0, bound 3000000)
main error: Could not convert timestamp 250412676419 for faad
main error: Timestamp conversion failed (delay 500000, buffering 0, bound 9000000)
main error: Could not convert timestamp 250411623238 for FFmpeg
main error: Timestamp conversion failed (delay 500000, buffering 0, bound 9000000)
main error: Could not convert timestamp 250412663238 for FFmpeg
main error: ES_OUT_SET_(GROUP_)PCR is called too late (pts_delay increased to 500 ms)
main error: buffer deadlock prevented

The UDP out is clean P1 p2 Error wise

But STB and VLC seem to lock up when playout programs change.

tested on current version on Debian10

logs below
[2021-05-13 12:34:04,890]  [av1 @ 0x561ad7000800] video_get_buffer: image parameters invalid
[2021-05-13 12:34:04,890]  [av1 @ 0x561ad7000800] get_buffer() failed
[2021-05-13 12:34:04,890]  [av1 @ 0x561ad7000800] thread_get_buffer() failed
[2021-05-13 12:34:04,890]  [av1 @ 0x561ad7000800] Failed to allocate space for current frame.
[2021-05-13 12:34:04,890]  [av1 @ 0x561ad7000800] Get current frame error

**Comment by jb-alvarado** [comment]
When you think this is a bug, please use the issue template bug report. 

When I don't have the settings and description of how to reproduce that error, I can not do anything.

**Comment by jb-alvarado** [comment]
When I create a multicast stream, with that output settings:

```YAML
ffmpeg_param: -c:v libx264 -crf 23 -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 1300k -bufsize 2600k -preset medium -profile:v Main -level 3.1 -c:a
        aac -ar 44100 -b:a 128k
stream_output: -flags +global_header -f mpegts udp://239.0.0.1:1234?ttl=13
```

And play this `udp://@239.0.0.1:1234` URL in VLC, I don't get any errors about timestamps. It is important that you really apply a re-compression to the output. Not only copy streams.
